### ISSUE TITLE
模型加个自定义名称字段，用来在消息中显示个性化名称

### ISSUE THREAD

**Issue by JeazW** [opentdp/wrest-chat#35]
## 加在这里：
![3bd8cc12b9fb5a6263fc4d8f6d32038](https://github.com/opentdp/wechat-rest/assets/75829171/ca021336-647e-4814-b060-b84b11fa6cd2)
## 显示在这里：

![20d0abf9d79b4c007880a64f51098c4](https://github.com/opentdp/wechat-rest/assets/75829171/f64dade8-6ae9-4da0-94c7-cce227fe5737)

**Comment by rehiy** [comment]
族类可以自定义的，字段说明写了

**Comment by rehiy** [comment]
以前是为了规范模型类别设计的，但实际上没并没有什么乱用，随便写自定义的就行了
