### ISSUE TITLE
可以将@绑定一个指令用于快捷操作吗？

### ISSUE THREAD

**Issue by myvica** [opentdp/wrest-chat#43]
有些高频的每次需要重复输入指令很麻烦，是否可以设置将 _@机器人微信_ 绑定某个指令？比如 `/ai` 。 这样每次只要 @ 一下机器人的微信就可以写内容了。

**Comment by rehiy** [comment]
参见 README.md Q5

**Comment by myvica** [comment]
这个与直接@机器人微信不一样，无论设置 `@微信名` 还是 `@昵称` 都没用

**Comment by dydhyhwu** [comment]
> 这个与直接@机器人微信不一样，无论设置 `@微信名` 还是 `@昵称` 都没用

1. 注意一下范围，通用可以直接全局
2. 如果给机器人设置的备注的话， 还要加一条记录`@备注`

**Comment by rehiy** [comment]
这个的原理并不是at，而是检测聊天内容中的关键词。所以如果有群昵称，需要特别设置下。这样做的原因是为了适配更多的自定义场景，实现 at 机器人可以响应其他的命令。

**Comment by myvica** [comment]
明白了，谢谢！
