### ISSUE TITLE
swagger 里的 /bot/cronjob/execute 方法没有 parameters

### ISSUE THREAD

**Issue by Kennytian** [opentdp/wrest-chat#52]
https://github.com/opentdp/wrest-chat/blob/master/public/swagger/swagger.json#L399

https://github.com/opentdp/wrest-chat/blob/master/httpd/wrobot/cronjob.go#L134
https://github.com/opentdp/wrest-chat/blob/master/wclient/crond/service.go#L45
https://github.com/opentdp/wrest-chat/blob/master/webview/src/openapi/wrobot.ts#L116

**Comment by rehiy** [comment]
done
