### ISSUE TITLE
请教/wcf/send_txt发送出去的消息怎么获取消息ID

### ISSUE THREAD

**Issue by dxlengye** [opentdp/wrest-chat#53]
如机器人发送的消息有误，需要通过自定义的指令来撤回。

但是通过接口发出去的，不会返回消息ID，WS里面也没有体现

请问能用什么方法解决

**Comment by rehiy** [comment]
根据消息，去数据库反查

**Comment by Jxells** [comment]
> 根据消息，去数据库反查

数据库获取的这个id不精确
