### ISSUE TITLE
http 和 ws 推送消息 严重漏消息啊 

### ISSUE THREAD

**Issue by WyntersN** [opentdp/wrest-chat#76]
![image](https://github.com/user-attachments/assets/40f0f31c-1a1a-452c-8d2a-3129861dc7d4)
发了2组 12345
http 和 ws 推送消息 严重漏消息啊

**Comment by Go-lu** [comment]
> ![image](https://private-user-images.githubusercontent.com/27792650/365318124-40f0f31c-1a1a-452c-8d2a-3129861dc7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njc5OTgsIm5iZiI6MTcyNTY2NzY5OCwicGF0aCI6Ii8yNzc5MjY1MC8zNjUzMTgxMjQtNDBmMGYzMWMtMWExYS00NTJjLThkMmEtMzEyOTg2MWRjN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OTIxNWRjNzljYzkzNjg2ZmJlMWY3YzI0NmNiNTljNGEwN2M5NGUzMmViMmYzNWNlMGRlODdjYWMzYzU5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-8wQwxFFOQtjBu-yxBHR8o-_hyt-4y_QgtPWhdNpMjU) 发了2组 12345 http 和 ws 推送消息 严重漏消息啊

帖主要不看看实时日志，我这ws消息挺正常的😂
![image](https://github.com/user-attachments/assets/d43d792c-91b6-4f4f-8ad5-a49b1cb4d1e0)

**Comment by WyntersN** [comment]
一秒发两条以上试试

**Comment by WyntersN** [comment]
是我的问题 我把推送机制改成了 随机推送一个，我不希望全部都推送，如果我多服务器ws连接
的话他推送的消息，我全部服务器都要去执行了！！！
